//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProject.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Aciklama {
            get {
                return ResourceManager.GetString("Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerini Değiştir.
        /// </summary>
        public static string BilgileriniDegistir {
            get {
                return ResourceManager.GetString("BilgileriniDegistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu aydaki çıkışlar.
        /// </summary>
        public static string BuAydakiCikislar {
            get {
                return ResourceManager.GetString("BuAydakiCikislar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu aydaki girişler.
        /// </summary>
        public static string BuAydakiGirisler {
            get {
                return ResourceManager.GetString("BuAydakiGirisler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Yönetim Sistemi.
        /// </summary>
        public static string BudgetManagementSystem {
            get {
                return ResourceManager.GetString("BudgetManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem geri alınamaz!.
        /// </summary>
        public static string BuIslemGeriAlinamaz {
            get {
                return ResourceManager.GetString("BuIslemGeriAlinamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Adı.
        /// </summary>
        public static string ButceAdi {
            get {
                return ResourceManager.GetString("ButceAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçeden Çıkart.
        /// </summary>
        public static string ButcedenCikart {
            get {
                return ResourceManager.GetString("ButcedenCikart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçeni Hesapla.
        /// </summary>
        public static string ButceHesapla {
            get {
                return ResourceManager.GetString("ButceHesapla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçelerinize herhangi bir katkı yapmalısınız.
        /// </summary>
        public static string ButceKatki {
            get {
                return ResourceManager.GetString("ButceKatki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçenizi artık daha kolay yönetin, böylelikle ay sonunda şaşırmayın!.
        /// </summary>
        public static string ButceKolaySasir {
            get {
                return ResourceManager.GetString("ButceKolaySasir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçeler.
        /// </summary>
        public static string Butceler {
            get {
                return ResourceManager.GetString("Butceler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçelerim.
        /// </summary>
        public static string Butcelerim {
            get {
                return ResourceManager.GetString("Butcelerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçene Ekle.
        /// </summary>
        public static string ButceneEkle {
            get {
                return ResourceManager.GetString("ButceneEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçeni Paylaş.
        /// </summary>
        public static string ButceniPaylas {
            get {
                return ResourceManager.GetString("ButceniPaylas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Paylaşımı.
        /// </summary>
        public static string ButcePaylasimi {
            get {
                return ResourceManager.GetString("ButcePaylasimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Sayısı.
        /// </summary>
        public static string ButceSayisi {
            get {
                return ResourceManager.GetString("ButceSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ButceSec {
            get {
                return ResourceManager.GetString("ButceSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Seçiniz.
        /// </summary>
        public static string ButceSeciniz {
            get {
                return ResourceManager.GetString("ButceSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Tipi.
        /// </summary>
        public static string ButceType {
            get {
                return ResourceManager.GetString("ButceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Oluştur.
        /// </summary>
        public static string CreateButce {
            get {
                return ResourceManager.GetString("CreateButce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Panel.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string Detay {
            get {
                return ResourceManager.GetString("Detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğer evinizde veya arkadaşınızla yaptığınız bir etkinlikte masrafları ve gelirleri paylaşacaksanız bütçe paylaşımı tam size göre!.
        /// </summary>
        public static string EgerEvinizdeveyaArkadasinizla {
            get {
                return ResourceManager.GetString("EgerEvinizdeveyaArkadasinizla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Geçersiz.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresinizi Giriniz!.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Çok Nelere Harcadın.
        /// </summary>
        public static string EnCokNelereHarcadin {
            get {
                return ResourceManager.GetString("EnCokNelereHarcadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evde, işte, her yerde bütçenizi kontrol edebilir, ihtiyaçlarınızı bütçenize uygun bir şekilde giderebilirsiniz..
        /// </summary>
        public static string EvdeIsteHer {
            get {
                return ResourceManager.GetString("EvdeIsteHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınızı Giriniz!.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelir Gider Pasta Grafiği.
        /// </summary>
        public static string GelirGiderPasta {
            get {
                return ResourceManager.GetString("GelirGiderPasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string GeriDon {
            get {
                return ResourceManager.GetString("GeriDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girişler.
        /// </summary>
        public static string Girisler {
            get {
                return ResourceManager.GetString("Girisler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Zamanı.
        /// </summary>
        public static string GirisZamani {
            get {
                return ResourceManager.GetString("GirisZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük, Haftalık ve Aylık raporlamalar ile bütçenizi ne kadar zorladığınızı görebilir tasarruf yapabilirsiniz..
        /// </summary>
        public static string GunlukHaftalik {
            get {
                return ResourceManager.GetString("GunlukHaftalik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Hacmi.
        /// </summary>
        public static string Hacim {
            get {
                return ResourceManager.GetString("Hacim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık Gelir Gider.
        /// </summary>
        public static string HaftalikGelirGider {
            get {
                return ResourceManager.GetString("HaftalikGelirGider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcanan.
        /// </summary>
        public static string Harcanan {
            get {
                return ResourceManager.GetString("Harcanan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap.
        /// </summary>
        public static string Hesap {
            get {
                return ResourceManager.GetString("Hesap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplamalar öncelikle ilk oluşturduğunuz varsayılan bütçe ile oluşturulmaktadır.
        /// </summary>
        public static string HesaplamaOncelikle {
            get {
                return ResourceManager.GetString("HesaplamaOncelikle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Iptal {
            get {
                return ResourceManager.GetString("Iptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişi.
        /// </summary>
        public static string Kisi {
            get {
                return ResourceManager.GetString("Kisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınızı Giriniz!.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string Miktar {
            get {
                return ResourceManager.GetString("Miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string Olustur {
            get {
                return ResourceManager.GetString("Olustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturma Tarihi.
        /// </summary>
        public static string OlusturmaTarihi {
            get {
                return ResourceManager.GetString("OlusturmaTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncelik.
        /// </summary>
        public static string Oncelik {
            get {
                return ResourceManager.GetString("Oncelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi Giriniz!.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaş.
        /// </summary>
        public static string Paylas {
            get {
                return ResourceManager.GetString("Paylas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaşılacak Kişinin Email Adresi.
        /// </summary>
        public static string PaylasilacakMail {
            get {
                return ResourceManager.GetString("PaylasilacakMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapınız.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        public static string Raporlar {
            get {
                return ResourceManager.GetString("Raporlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Giriş ve Çıkışların.
        /// </summary>
        public static string SonGirisCikis {
            get {
                return ResourceManager.GetString("SonGirisCikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşınabilirlik.
        /// </summary>
        public static string Tasinabilirlik {
            get {
                return ResourceManager.GetString("Tasinabilirlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam İşlem Sayısı.
        /// </summary>
        public static string ToplamIslemSayisi {
            get {
                return ResourceManager.GetString("ToplamIslemSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Bütçelerim.
        /// </summary>
        public static string TumButcelerim {
            get {
                return ResourceManager.GetString("TumButcelerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türü.
        /// </summary>
        public static string Turu {
            get {
                return ResourceManager.GetString("Turu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler.
        /// </summary>
        public static string Uyeler {
            get {
                return ResourceManager.GetString("Uyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsayılan Bütçe.
        /// </summary>
        public static string VarsayilanButce {
            get {
                return ResourceManager.GetString("VarsayilanButce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki.
        /// </summary>
        public static string Yetki {
            get {
                return ResourceManager.GetString("Yetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Seçenekleri.
        /// </summary>
        public static string YoneticiSecenekleri {
            get {
                return ResourceManager.GetString("YoneticiSecenekleri", resourceCulture);
            }
        }
    }
}
