//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joins
    {
        public int PID { get; set; }
        public int BID { get; set; }
        public int UID { get; set; }
    
        public virtual Budgets Budgets { get; set; }
        public virtual Users Users { get; set; }
    }
}
