//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurlar
    {
        public int KID { get; set; }
        public Nullable<int> PBID { get; set; }
        public Nullable<double> Kur { get; set; }
    
        public virtual ParaBirimleri ParaBirimleri { get; set; }
    }
}
