//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Action = new HashSet<Action>();
            this.Girisler = new HashSet<Girisler>();
            this.Joins = new HashSet<Joins>();
        }
    
        public int UID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> DefaultBudget { get; set; }
        public int Yetki { get; set; }
        public Nullable<int> Sehir { get; set; }
        public Nullable<decimal> IslemHacmi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action { get; set; }
        public virtual Budgets Budgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Girisler> Girisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Joins> Joins { get; set; }
        public virtual Yetkiler Yetkiler { get; set; }
        public virtual Iller Iller { get; set; }
    }
}
